# -*- coding: utf-8 -*-
"""Demographics Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwGY1Gf_k9nvnj42DgHZ_iZqG2xAGhIY

# Demographics Analysis:
### Process of collecting insights about charachteristics of a group of people. To be precise focuses on age, race, gender, income, education, employment, etc.

### **EXPECTED RESULTS** : Provides insights about the visitors, how diff demographic groups interact with the site, and which segments are underrated or valuable accordingly.

### **ADVANTAGE** : Businesses can tailor their marketing strategies, content and UX to meet the customer needs, concluding to drive better engagement, reaching to target audiences, and leading to customer satisfaction.
"""

import pandas as pd
data = pd.read_csv('user_demographics.csv')
data.head()

data.describe()

"""Time is in seconds.

# **GEOGRAPHIC DISTRIBUTION**

# To check areas having maxi user counts
"""

import seaborn as sns
import matplotlib.pyplot as plt

top_cities = data.sort_values(by='Users', ascending=False).head(15)

plt.figure(figsize=(12, 10))
sns.barplot(y=top_cities['Town/City'], x=top_cities['Users'], palette='YlGnBu')
plt.xlabel('Number of Users')
plt.ylabel('Town/City')
plt.title('Top 15 Cities by Number of Users')
plt.show()

"""### **CONCLUSION** : Top 3 cities in terms of most users, Hyderabad, Bengaluru, Chennai. Steep decrease in user count indicates more users in urban cities.

# Engagement Rate across top cities
"""

plt.figure(figsize=(12,10))
sns.barplot(x=top_cities['Engagement rate'], y=top_cities['Town/City'], palette='spring')
plt.xlabel('Engagement Rate')
plt.ylabel('Town/City')
plt.title('Engagement Rate in top 15 cities')
plt.show()

"""### **CONCLUSION** : Hyderabad, Bengaluru, Chennai, exhibit the highest engagement rates.

# Average number of engaged sessions per user
"""

plt.figure(figsize=(12,10))
sns.barplot(x=top_cities['Engaged sessions per user'], y=top_cities['Town/City'], palette='plasma')
plt.xlabel('Engaged sessions per user')
plt.ylabel('Town/City')
plt.title('Engaged sessions per user in top 15 cities')
plt.show()

"""### **CONCLUSION** :  Hyderabad, and Bengaluru have the highest engagement sessions per user. Indicating the users in these cities interact most frequently with the business website

# Average Engagement Time
"""

plt.figure(figsize=(12,10))
sns.barplot(x=top_cities['Average engagement time'], y=top_cities['Town/City'], palette='crest')
plt.xlabel('Average engagement time (in seconds)')
plt.ylabel('Town/City')
plt.title('Average Engagement Time in top 15 cities by number of users')
plt.show()

"""### **CONCLUSION** : Lucknow, Vishakhapatnam, and Kochi show the highest engagement time.

# Comparing new vs returning users in top 15 cities
"""

top_cities['Returning users'] = top_cities['Users'] - top_cities['New users']

top_cities_melted = top_cities.melt(id_vars='Town/City', value_vars=['New users', 'Returning users'],
                                    var_name='User Type', value_name='Count')

plt.figure(figsize=(12,10))
sns.barplot(x='Count', y='Town/City', hue='User Type', data=top_cities_melted, palette='viridis')
plt.xlabel('Number of Users')
plt.ylabel('Town/City')
plt.title('New Users vs Returning Users in top 15 cities based on Number of Users')
plt.legend()
plt.show()

"""### **CONCLUSION** : This data reveals  majority are new users, in which Hyderabad, Bengaluru, and Chennai have the highest counts. Suggesting more no. of first time users, but very less returning users rate, which indicates need of improvement in user retention strategies.

# Event Counts
"""

plt.figure(figsize=(12,10))
sns.barplot(x=top_cities['Event count'], y=top_cities['Town/City'], palette='magma')
plt.xlabel('Event Count')
plt.ylabel('Town/City')
plt.title('Event Count in top 15 cities based on number of users')
plt.show()

"""### **CONLCUSION** : Hyderabad and Bengaluru leading significantly with the highest event counts, resulting in high level of user interactions. Chennai and Mumbai on the next lead. Cities like Kochi, Vishakhapatnam, and Lucknow, having relatively lower event counts, resulting in least user interaction."""